# Generated by Django 2.1.7 on 2019-03-04 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('tv_shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='average',
            field=models.DecimalField(decimal_places=1, default=7, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvshow',
            name='genre',
            field=models.ForeignKey(default=7.0, on_delete=django.db.models.deletion.CASCADE, to='genres.Genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tvshow',
            name='storyline',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
