# Generated by Django 2.1.7 on 2019-03-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0002_auto_20190304_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='average',
        ),
    ]
